---
- name: Update and upgrade all servers
  hosts: cluster_servers
  become: yes
  tasks:
    - name: Run apt update
      shell: apt update -y

    - name: Run apt upgrade with custom options
      shell: apt upgrade -o Dpkg::Options::="--force-confold" -y

